import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, Share2, Copy, MessageCircle, Facebook, Twitter, Send, Download, Check, Image } from 'lucide-react';
import { useLanguage } from '../contexts/LanguageContext';
import {
    ShareData,
    generateShareText,
    copyToClipboard,
    getWhatsAppShareUrl,
    getFacebookShareUrl,
    getTwitterShareUrl,
    getTelegramShareUrl,
    nativeShare,
    downloadAsText
} from '../utils/shareUtils';
import { downloadChartAsImage, shareChartAsImage, getChartImageDataUrl } from '../utils/chartImageGenerator';

interface ShareModalProps {
    isOpen: boolean;
    onClose: () => void;
    shareData: ShareData;
}

const ShareModal: React.FC<ShareModalProps> = ({ isOpen, onClose, shareData }) => {
    const { language, t } = useLanguage();
    const [copied, setCopied] = useState(false);
    const [downloading, setDownloading] = useState(false);
    const [sharing, setSharing] = useState(false);
    const isTamil = language === 'ta';

    const handleCopyText = async () => {
        const text = generateShareText(shareData, language);
        const success = await copyToClipboard(text);
        if (success) {
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        }
    };

    const handleNativeShare = async () => {
        const success = await nativeShare(shareData, language);
        if (!success) {
            // Fallback to copy
            handleCopyText();
        }
    };

    const handleDownloadImage = async () => {
        setDownloading(true);
        try {
            const filename = `${shareData.name.replace(/\s+/g, '_')}_chart.png`;
            await downloadChartAsImage('chart-container', filename, {
                watermarkText: isTamil ? 'SivaAstro மூலம் உருவாக்கப்பட்டது' : 'Generated by SivaAstro',
                includeTimestamp: true
            });
        } catch (error) {
            console.error('Failed to download image:', error);
        } finally {
            setDownloading(false);
        }
    };

    const handleShareImage = async () => {
        setSharing(true);
        try {
            const text = generateShareText(shareData, language);
            const success = await shareChartAsImage('chart-container', text, {
                watermarkText: isTamil ? 'SivaAstro மூலம் உருவாக்கப்பட்டது' : 'Generated by SivaAstro',
                includeTimestamp: true
            });

            if (!success) {
                // Fallback to download if share not supported
                await handleDownloadImage();
            }
        } catch (error) {
            console.error('Failed to share image:', error);
        } finally {
            setSharing(false);
        }
    };

    const shareOptions = [
        {
            name: isTamil ? 'WhatsApp இல் பகிர்' : 'Share on WhatsApp',
            icon: MessageCircle,
            color: 'from-green-500 to-green-600',
            action: () => {
                const text = generateShareText(shareData, language);
                window.open(getWhatsAppShareUrl(text), '_blank');
            }
        },
        {
            name: isTamil ? 'Facebook இல் பகிர்' : 'Share on Facebook',
            icon: Facebook,
            color: 'from-blue-500 to-blue-600',
            action: () => {
                const text = generateShareText(shareData, language);
                window.open(getFacebookShareUrl(text), '_blank');
            }
        },
        {
            name: isTamil ? 'Twitter இல் பகிர்' : 'Share on Twitter',
            icon: Twitter,
            color: 'from-sky-400 to-blue-500',
            action: () => {
                const text = generateShareText(shareData, language);
                window.open(getTwitterShareUrl(text), '_blank');
            }
        },
        {
            name: isTamil ? 'Telegram இல் பகிர்' : 'Share on Telegram',
            icon: Send,
            color: 'from-cyan-400 to-blue-500',
            action: () => {
                const text = generateShareText(shareData, language);
                window.open(getTelegramShareUrl(text), '_blank');
            }
        }
    ];

    return (
        <AnimatePresence>
            {isOpen && (
                <>
                    {/* Backdrop */}
                    <motion.div
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        exit={{ opacity: 0 }}
                        className="fixed inset-0 bg-black/70 backdrop-blur-sm z-50"
                        onClick={onClose}
                    />

                    {/* Modal */}
                    <motion.div
                        initial={{ opacity: 0, scale: 0.9, y: 20 }}
                        animate={{ opacity: 1, scale: 1, y: 0 }}
                        exit={{ opacity: 0, scale: 0.9, y: 20 }}
                        className="fixed inset-0 z-50 flex items-center justify-center p-4"
                    >
                        <div className="bg-gradient-to-br from-slate-900 to-slate-950 rounded-2xl shadow-2xl border border-purple-500/30 w-full max-w-md max-h-[90vh] overflow-y-auto">
                            {/* Header */}
                            <div className="flex items-center justify-between p-6 border-b border-white/10">
                                <div className="flex items-center gap-3">
                                    <div className="p-2 bg-purple-500/20 rounded-lg">
                                        <Share2 className="w-6 h-6 text-purple-400" />
                                    </div>
                                    <h2 className="text-2xl font-bold text-white">
                                        {isTamil ? 'கட்டத்தை பகிர்' : 'Share Your Chart'}
                                    </h2>
                                </div>
                                <button
                                    onClick={onClose}
                                    className="p-2 hover:bg-white/10 rounded-lg transition-colors"
                                >
                                    <X className="w-5 h-5 text-slate-400" />
                                </button>
                            </div>

                            {/* Content */}
                            <div className="p-6 space-y-6">
                                {/* Preview Text */}
                                <div className="bg-slate-800/50 rounded-lg p-4 border border-slate-700">
                                    <p className="text-sm text-slate-400 mb-2">
                                        {isTamil ? 'முன்னோ ட்டம்' : 'Preview'}
                                    </p>
                                    <p className="text-slate-300 text-sm whitespace-pre-line">
                                        {generateShareText(shareData, language)}
                                    </p>
                                </div>

                                {/* Copy & Download Actions */}
                                <div className="grid grid-cols-2 gap-3">
                                    <button
                                        onClick={handleCopyText}
                                        className="flex items-center justify-center gap-2 px-4 py-3 bg-slate-800 hover:bg-slate-700 border border-slate-600 rounded-lg transition-all text-sm font-medium"
                                    >
                                        {copied ? (
                                            <>
                                                <Check className="w-4 h-4 text-green-400" />
                                                <span className="text-green-400">
                                                    {isTamil ? 'நகலெடுக்கப்பட்டது!' : 'Copied!'}
                                                </span>
                                            </>
                                        ) : (
                                            <>
                                                <Copy className="w-4 h-4" />
                                                <span>{isTamil ? 'நகல்' : 'Copy Text'}</span>
                                            </>
                                        )}
                                    </button>

                                    <button
                                        onClick={handleDownloadImage}
                                        disabled={downloading}
                                        className="flex items-center justify-center gap-2 px-4 py-3 bg-gradient-to-r from-amber-500 to-orange-600 hover:from-amber-400 hover:to-orange-500 border border-amber-400/30 rounded-lg transition-all text-white font-medium disabled:opacity-50 disabled:cursor-not-allowed"
                                    >
                                        {downloading ? (
                                            <>
                                                <Download className="w-4 h-4 animate-bounce" />
                                                <span>{isTamil ? 'பதிவிறக்குகிறது...' : 'Generating...'}</span>
                                            </>
                                        ) : (
                                            <>
                                                <Image className="w-4 h-4" />
                                                <span>{isTamil ? 'படமாக பதிவிறக்கு' : 'Download Image'}</span>
                                            </>
                                        )}
                                    </button>
                                </div>

                                {/* Share Image Button - prominently featured */}
                                <button
                                    onClick={handleShareImage}
                                    disabled={sharing}
                                    className="w-full flex items-center justify-center gap-2 px-4 py-4 bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-500 hover:to-pink-500 rounded-lg transition-all text-white font-bold text-lg shadow-lg disabled:opacity-50 disabled:cursor-not-allowed"
                                >
                                    {sharing ? (
                                        <>
                                            <Share2 className="w-5 h-5 animate-pulse" />
                                            <span>{isTamil ? 'பகிர்கிறது...' : 'Sharing...'}</span>
                                        </>
                                    ) : (
                                        <>
                                            <Share2 className="w-5 h-5" />
                                            <span>{isTamil ? '📸 படத்தை பகிர்' : '📸 Share Chart Image'}</span>
                                        </>
                                    )}
                                </button>

                                <p className="text-center text-xs text-slate-500">
                                    {isTamil ? 'WhatsApp, Telegram மற்றும் மற்ற பயன்பாடுகளுக்கு படம் பகிரவும்' : 'Share image to WhatsApp, Telegram & other apps'}
                                </p>

                                {/* Share Options */}
                                <div className="space-y-3">
                                    <p className="text-sm font-medium text-slate-400">
                                        {isTamil ? 'இதில் பகிர்' : 'Share on'}
                                    </p>
                                    <div className="grid gap-2">
                                        {shareOptions.map((option, index) => {
                                            const Icon = option.icon;
                                            return (
                                                <button
                                                    key={index}
                                                    onClick={option.action}
                                                    className={`flex items-center gap-3 px-4 py-3 bg-gradient-to-r ${option.color} hover:shadow-lg hover:scale-[1.02] active:scale-[0.98] rounded-lg transition-all text-white font-medium`}
                                                >
                                                    <Icon className="w-5 h-5" />
                                                    <span>{option.name}</span>
                                                </button>
                                            );
                                        })}
                                    </div>
                                </div>

                                {/* Native Share (Mobile) */}
                                {typeof navigator !== 'undefined' && 'share' in navigator && (
                                    <button
                                        onClick={handleNativeShare}
                                        className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-purple-600 hover:bg-purple-500 rounded-lg transition-all text-white font-medium"
                                    >
                                        <Share2 className="w-5 h-5" />
                                        <span>{isTamil ? 'மேலும் பகிர்...' : 'More Share Options...'}</span>
                                    </button>
                                )}
                            </div>
                        </div>
                    </motion.div>
                </>
            )}
        </AnimatePresence>
    );
};

export default ShareModal;
