// Chart Image Generator
// Converts chart HTML to downloadable image with watermark

import html2canvas from 'html2canvas';

export interface ChartImageOptions {
    watermarkText?: string;
    quality?: number;
    backgroundColor?: string;
    includeTimestamp?: boolean;
}

/**
 * Capture chart element as image and download
 */
export async function downloadChartAsImage(
    elementId: string,
    filename: string = 'astrological_chart.png',
    options: ChartImageOptions = {}
): Promise<boolean> {
    const {
        watermarkText = 'Generated by SivaAstro',
        quality = 0.95,
        backgroundColor = '#0f172a', // slate-900
        includeTimestamp = true
    } = options;

    try {
        const element = document.getElementById(elementId);
        if (!element) {
            console.error(`Element with ID "${elementId}" not found`);
            return false;
        }

        // Create canvas from element
        const canvas = await html2canvas(element, {
            backgroundColor,
            scale: 2, // Higher resolution
            logging: false,
            useCORS: true,
            allowTaint: false,
            foreignObjectRendering: false,
            onclone: (clonedDoc, clonedElement) => {
                // Aggressively copy ALL computed styles to inline to convert oklch to RGB
                const allElements = clonedElement.querySelectorAll('*');
                const originalElements = element.querySelectorAll('*');

                // Process the root element too
                const elementsToProcess = [clonedElement, ...Array.from(allElements)];
                const originalElementsArray = [element, ...Array.from(originalElements)];

                elementsToProcess.forEach((clonedEl: any, index) => {
                    const originalEl = originalElementsArray[index];
                    if (!originalEl) return;

                    try {
                        const computed = window.getComputedStyle(originalEl);

                        // Copy all color-related properties
                        const colorProps = [
                            'color',
                            'backgroundColor',
                            'borderColor',
                            'borderTopColor',
                            'borderRightColor',
                            'borderBottomColor',
                            'borderLeftColor',
                            'outlineColor',
                            'textDecorationColor',
                            'caretColor',
                            'columnRuleColor'
                        ];

                        colorProps.forEach(prop => {
                            try {
                                const value = computed.getPropertyValue(prop);
                                if (value && value !== 'rgba(0, 0, 0, 0)' && value !== 'transparent') {
                                    clonedEl.style[prop] = value;
                                }
                            } catch (e) {
                                // Skip if error
                            }
                        });
                    } catch (e) {
                        // Skip element if error
                        console.warn('Error processing element:', e);
                    }
                });
            }
        });

        // Add watermark
        const ctx = canvas.getContext('2d');
        if (ctx) {
            addWatermark(ctx, canvas.width, canvas.height, watermarkText, includeTimestamp);
        }

        // Convert to blob and download
        canvas.toBlob((blob) => {
            if (!blob) {
                console.error('Failed to create blob from canvas');
                return;
            }

            const url = URL.createObjectURL(blob);
            const link = document.createElement('a');
            link.href = url;
            link.download = filename;
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
            URL.revokeObjectURL(url);
        }, 'image/png', quality);

        return true;
    } catch (error) {
        console.error('Error generating chart image:', error);
        return false;
    }
}

/**
 * Add watermark to canvas
 */
function addWatermark(
    ctx: CanvasRenderingContext2D,
    width: number,
    height: number,
    text: string,
    includeTimestamp: boolean
): void {
    // Semi-transparent overlay at bottom
    const overlayHeight = 60;
    ctx.fillStyle = 'rgba(0, 0, 0, 0.7)';
    ctx.fillRect(0, height - overlayHeight, width, overlayHeight);

    // Watermark text
    ctx.fillStyle = '#a78bfa'; // purple-400
    ctx.font = 'bold 20px Inter, sans-serif';
    ctx.textAlign = 'left';
    ctx.fillText(text, 20, height - 30);

    // Timestamp
    if (includeTimestamp) {
        const timestamp = new Date().toLocaleDateString('en-US', {
            year: 'numeric',
            month: 'short',
            day: 'numeric'
        });
        ctx.fillStyle = '#94a3b8'; // slate-400
        ctx.font = '14px Inter, sans-serif';
        ctx.textAlign = 'right';
        ctx.fillText(timestamp, width - 20, height - 30);
    }

    // Add logo/star symbol
    ctx.fillStyle = '#fbbf24'; // amber-400
    ctx.font = 'bold 30px serif';
    ctx.textAlign = 'center';
    ctx.fillText('⭐', width / 2, height - 20);
}

/**
 * Share chart image via Web Share API (mobile)
 */
export async function shareChartAsImage(
    elementId: string,
    shareText: string,
    options: ChartImageOptions = {}
): Promise<boolean> {
    if (!navigator.share || !navigator.canShare) {
        return false;
    }

    try {
        const element = document.getElementById(elementId);
        if (!element) return false;

        const canvas = await html2canvas(element, {
            backgroundColor: options.backgroundColor || '#0f172a',
            scale: 2,
            logging: false
        });

        // Add watermark
        const ctx = canvas.getContext('2d');
        if (ctx) {
            addWatermark(ctx, canvas.width, canvas.height, options.watermarkText || 'Generated by SivaAstro', options.includeTimestamp !== false);
        }

        // Convert to blob
        const blob = await new Promise<Blob | null>((resolve) => {
            canvas.toBlob(resolve, 'image/png', options.quality || 0.95);
        });

        if (!blob) return false;

        const file = new File([blob], 'astrological_chart.png', { type: 'image/png' });

        if (navigator.canShare({ files: [file] })) {
            await navigator.share({
                text: shareText,
                files: [file]
            });
            return true;
        }

        return false;
    } catch (error) {
        console.error('Error sharing chart image:', error);
        return false;
    }
}

/**
 * Get chart image as data URL (for preview)
 */
export async function getChartImageDataUrl(
    elementId: string,
    options: ChartImageOptions = {}
): Promise<string | null> {
    try {
        const element = document.getElementById(elementId);
        if (!element) return null;

        const canvas = await html2canvas(element, {
            backgroundColor: options.backgroundColor || '#0f172a',
            scale: 2,
            logging: false
        });

        const ctx = canvas.getContext('2d');
        if (ctx) {
            addWatermark(ctx, canvas.width, canvas.height, options.watermarkText || 'Generated by SivaAstro', options.includeTimestamp !== false);
        }

        return canvas.toDataURL('image/png', options.quality || 0.95);
    } catch (error) {
        console.error('Error getting chart image data URL:', error);
        return null;
    }
}
