// Chart Image Generator (using dom-to-image-more)
// Converts chart HTML to downloadable image with watermark

import domtoimage from 'dom-to-image-more';

export interface ChartImageOptions {
    watermarkText?: string;
    quality?: number;
    backgroundColor?: string;
    includeTimestamp?: boolean;
}

/**
 * Capture chart element as image and download
 */
export async function downloadChartAsImage(
    elementId: string,
    filename: string = 'astrological_chart.png',
    options: ChartImageOptions = {}
): Promise<boolean> {
    const {
        watermarkText = 'Generated by AstroZen',
        quality = 0.95,
        backgroundColor = '#0f172a', // slate-900
        includeTimestamp = true
    } = options;

    try {
        const element = document.getElementById(elementId);
        if (!element) {
            console.error(`Element with ID "${elementId}" not found`);
            return false;
        }

        // Convert to blob using dom-to-image
        const blob = await domtoimage.toBlob(element, {
            bgcolor: backgroundColor,
            quality: quality,
            cacheBust: true,
            style: {
                margin: '0',
                padding: '20px'
            }
        });

        // Create a canvas to add watermark
        const img = await createImageBitmap(blob);
        const canvas = document.createElement('canvas');
        canvas.width = img.width;
        canvas.height = img.height + 60; // Extra space for watermark

        const ctx = canvas.getContext('2d');
        if (!ctx) {
            console.error('Failed to get canvas context');
            return false;
        }

        // Draw the chart image
        ctx.drawImage(img, 0, 0);

        // Add watermark
        addWatermark(ctx, canvas.width, canvas.height, watermarkText, includeTimestamp);

        // Convert to blob and download
        canvas.toBlob((finalBlob) => {
            if (!finalBlob) {
                console.error('Failed to create final blob');
                return;
            }

            const url = URL.createObjectURL(finalBlob);
            const link = document.createElement('a');
            link.href = url;
            link.download = filename;
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
            URL.revokeObjectURL(url);
        }, 'image/png', quality);

        return true;
    } catch (error) {
        console.error('Error generating chart image:', error);
        return false;
    }
}

/**
 * Add watermark to canvas
 */
function addWatermark(
    ctx: CanvasRenderingContext2D,
    width: number,
    height: number,
    text: string,
    includeTimestamp: boolean
): void {
    // Semi-transparent overlay at bottom
    const overlayHeight = 60;
    ctx.fillStyle = 'rgba(0, 0, 0, 0.7)';
    ctx.fillRect(0, height - overlayHeight, width, overlayHeight);

    // Watermark text
    ctx.fillStyle = '#a78bfa'; // purple-400
    ctx.font = 'bold 20px Inter, sans-serif';
    ctx.textAlign = 'left';
    ctx.fillText(text, 20, height - 30);

    // Timestamp
    if (includeTimestamp) {
        const timestamp = new Date().toLocaleDateString('en-US', {
            year: 'numeric',
            month: 'short',
            day: 'numeric'
        });
        ctx.fillStyle = '#94a3b8'; // slate-400
        ctx.font = '14px Inter, sans-serif';
        ctx.textAlign = 'right';
        ctx.fillText(timestamp, width - 20, height - 30);
    }

    // Add logo/star symbol
    ctx.fillStyle = '#fbbf24'; // amber-400
    ctx.font = 'bold 30px serif';
    ctx.textAlign = 'center';
    ctx.fillText('⭐', width / 2, height - 20);
}

/**
 * Share chart image via Web Share API (mobile)
 */
export async function shareChartAsImage(
    elementId: string,
    shareText: string,
    options: ChartImageOptions = {}
): Promise<boolean> {
    if (!navigator.share) {
        return false;
    }

    try {
        const element = document.getElementById(elementId);
        if (!element) return false;

        const blob = await domtoimage.toBlob(element, {
            bgcolor: options.backgroundColor || '#0f172a',
            quality: options.quality || 0.95
        });

        const file = new File([blob], 'astrological_chart.png', { type: 'image/png' });

        if (navigator.canShare && navigator.canShare({ files: [file] })) {
            await navigator.share({
                text: shareText,
                files: [file]
            });
            return true;
        }

        return false;
    } catch (error) {
        console.error('Error sharing chart image:', error);
        return false;
    }
}

/**
 * Get chart image as data URL (for preview)
 */
export async function getChartImageDataUrl(
    elementId: string,
    options: ChartImageOptions = {}
): Promise<string | null> {
    try {
        const element = document.getElementById(elementId);
        if (!element) return null;

        const dataUrl = await domtoimage.toPng(element, {
            bgcolor: options.backgroundColor || '#0f172a',
            quality: options.quality || 0.95
        });

        return dataUrl;
    } catch (error) {
        console.error('Error getting chart image data URL:', error);
        return null;
    }
}
