import * as domtoimage from 'dom-to-image-more';
import jsPDF from 'jspdf';

/**
 * Generate shareable text summary of matching results
 */
export const generateMatchingSummaryText = (
    boyName: string,
    girlName: string,
    result: any,
    isTamil: boolean = false
): string => {
    const title = isTamil
        ? `🔮 திருமண பொருத்த முடிவுகள் - ${boyName} ♂ & ${girlName} ♀`
        : `🔮 Marriage Matching Results - ${boyName} ♂ & ${girlName} ♀`;

    const score = `📊 ${isTamil ? 'மதிப்பெண்' : 'Overall Score'}: ${result.overallScore.toFixed(1)}/100`;
    const verdict = `✨ ${isTamil ? 'முடிவு' : 'Verdict'}: ${result.verdict}`;

    const lagna = isTamil
        ? `\n🎭 லக்ன பகுப்பாய்வு:\n${boyName}: ${result.lagnaAnalysis.boyType}\n${girlName}: ${result.lagnaAnalysis.girlType}`
        : `\n🎭 Lagna Analysis:\n${boyName}: ${result.lagnaAnalysis.boyType}\n${girlName}: ${result.lagnaAnalysis.girlType}`;

    const settlement = isTamil
        ? `\n🌍 வெளிநாடு/சொந்த ஊர்:\n${boyName}: ${result.houseMatching.house12.boyYoga} Yoga\n${girlName}: ${result.houseMatching.house12.girlYoga} Yoga`
        : `\n🌍 Foreign/Local Settlement:\n${boyName}: ${result.houseMatching.house12.boyYoga} Yoga\n${girlName}: ${result.houseMatching.house12.girlYoga} Yoga`;

    const dasa = isTamil
        ? `\n⏰ தற்போதைய தசா:\n${boyName}: ${result.dasaMatching.boyCurrentDasa} / ${result.dasaMatching.boyCurrentBhukti}\n${girlName}: ${result.dasaMatching.girlCurrentDasa} / ${result.dasaMatching.girlCurrentBhukti}`
        : `\n⏰ Current Dasa:\n${boyName}: ${result.dasaMatching.boyCurrentDasa} / ${result.dasaMatching.boyCurrentBhukti}\n${girlName}: ${result.dasaMatching.girlCurrentDasa} / ${result.dasaMatching.girlCurrentBhukti}`;

    const footer = isTamil
        ? `\n\n💫 சிவாஸ்ட்ரோ பயன்பாட்டால் தயாரிக்கப்பட்டது`
        : `\n\n💫 Generated by SivaAstro App`;

    return `${title}\n\n${score}\n${verdict}${lagna}${settlement}${dasa}${footer}`;
};

/**
 * Download results as image
 */
export const downloadMatchingResultsAsImage = async (
    elementId: string,
    boyName: string,
    girlName: string
): Promise<void> => {
    const element = document.getElementById(elementId);
    if (!element) {
        throw new Error('Results element not found');
    }

    const dataUrl = await domtoimage.toPng(element, {
        quality: 1.0,
        bgcolor: '#0f172a',
        style: {
            transform: 'scale(1)',
            transformOrigin: 'top left'
        }
    });

    const link = document.createElement('a');
    link.download = `marriage-matching-${boyName}-${girlName}.png`;
    link.href = dataUrl;
    link.click();
};

/**
 * Download results as PDF
 */
export const downloadMatchingResultsAsPDF = async (
    elementId: string,
    boyName: string,
    girlName: string
): Promise<void> => {
    const element = document.getElementById(elementId);
    if (!element) {
        throw new Error('Results element not found');
    }

    const dataUrl = await domtoimage.toPng(element, {
        quality: 1.0,
        bgcolor: '#0f172a',
        style: {
            transform: 'scale(1)',
            transformOrigin: 'top left'
        }
    });

    // Create image to get dimensions
    const img = new Image();
    img.src = dataUrl;
    await new Promise((resolve) => {
        img.onload = resolve;
    });

    const pdf = new jsPDF({
        orientation: img.width > img.height ? 'landscape' : 'portrait',
        unit: 'px',
        format: [img.width, img.height]
    });

    pdf.addImage(dataUrl, 'PNG', 0, 0, img.width, img.height);
    pdf.save(`marriage-matching-${boyName}-${girlName}.pdf`);
};

/**
 * Share results via Web Share API or fallback to social media
 */
export const shareMatchingResults = async (
    text: string,
    title: string,
    url?: string
): Promise<void> => {
    if (navigator.share) {
        try {
            await navigator.share({
                title,
                text,
                url: url || window.location.href
            });
        } catch (error) {
            console.error('Error sharing:', error);
        }
    } else {
        // Fallback: copy to clipboard
        await navigator.clipboard.writeText(text);
        alert('Results copied to clipboard!');
    }
};

/**
 * Share via WhatsApp
 */
export const shareViaWhatsApp = (text: string): void => {
    const url = `https://wa.me/?text=${encodeURIComponent(text)}`;
    window.open(url, '_blank');
};

/**
 * Copy results to clipboard
 */
export const copyToClipboard = async (text: string): Promise<void> => {
    await navigator.clipboard.writeText(text);
};
