// Share Utilities for Chart Sharing
// Handles social media share URLs, clipboard, and text generation

export interface ShareData {
    name: string;
    lagna: string;
    moonSign: string;
    birthDate: string;
    birthTime: string;
    birthPlace: string;
}

/**
 * Generate shareable text summary
 */
export function generateShareText(data: ShareData, language: 'en' | 'ta' = 'en'): string {
    if (language === 'ta') {
        return `🌟 எனது ஜோதிட கட்டம் 🌟

பெயர்: ${data.name}
லக்னம்: ${data.lagna}
ராசி (சந்திரன்): ${data.moonSign}
பிறப்பு: ${data.birthDate} @ ${data.birthTime}
இடம்: ${data.birthPlace}

AstroZen மூலம் உருவாக்கப்பட்டது`;
    }

    return `🌟 My Vedic Astrology Chart 🌟

Name: ${data.name}
Lagna (Ascendant): ${data.lagna}
Moon Sign: ${data.moonSign}
Birth: ${data.birthDate} @ ${data.birthTime}
Place: ${data.birthPlace}

Generated by AstroZen`;
}

/**
 * Copy text to clipboard
 */
export async function copyToClipboard(text: string): Promise<boolean> {
    try {
        await navigator.clipboard.writeText(text);
        return true;
    } catch (error) {
        // Fallback for older browsers
        try {
            const textArea = document.createElement('textarea');
            textArea.value = text;
            textArea.style.position = 'fixed';
            textArea.style.left = '-999999px';
            document.body.appendChild(textArea);
            textArea.select();
            document.execCommand('copy');
            document.body.removeChild(textArea);
            return true;
        } catch (fallbackError) {
            console.error('Failed to copy:', fallbackError);
            return false;
        }
    }
}

/**
 * Generate WhatsApp share URL
 */
export function getWhatsAppShareUrl(text: string): string {
    const encodedText = encodeURIComponent(text);
    return `https://wa.me/?text=${encodedText}`;
}

/**
 * Generate Facebook share URL
 */
export function getFacebookShareUrl(text: string): string {
    const url = window.location.href;
    const encodedUrl = encodeURIComponent(url);
    const encodedText = encodeURIComponent(text);
    return `https://www.facebook.com/sharer/sharer.php?u=${encodedUrl}&quote=${encodedText}`;
}

/**
 * Generate Twitter share URL
 */
export function getTwitterShareUrl(text: string): string {
    const encodedText = encodeURIComponent(text);
    const hashtags = 'VedicAstrology,AstroZen,Jothidam';
    return `https://twitter.com/intent/tweet?text=${encodedText}&hashtags=${hashtags}`;
}

/**
 * Generate Telegram share URL
 */
export function getTelegramShareUrl(text: string): string {
    const encodedText = encodeURIComponent(text);
    return `https://t.me/share/url?url=${encodeURIComponent(window.location.href)}&text=${encodedText}`;
}

/**
 * Open share dialog (Web Share API if available)
 */
export async function nativeShare(data: ShareData, language: 'en' | 'ta' = 'en'): Promise<boolean> {
    if (!navigator.share) {
        return false;
    }

    try {
        const text = generateShareText(data, language);
        await navigator.share({
            title: language === 'ta' ? 'எனது ஜோதிட கட்டம்' : 'My Vedic Chart',
            text: text,
            url: window.location.href
        });
        return true;
    } catch (error) {
        // User cancelled or error occurred
        return false;
    }
}

/**
 * Download text as file
 */
export function downloadAsText(data: ShareData, language: 'en' | 'ta' = 'en'): void {
    const text = generateShareText(data, language);
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${data.name.replace(/\s+/g, '_')}_chart.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}
